Repository solutionchallenge/ondaum-client, pull requests merged in 2025-05, with the labels that each got.

#23 Feat/#16/onboarding-basic
  index.html
  package-lock.json
  package.json
  src/commons/inputs/Button/index.tsx
  src/commons/inputs/ToggleButton/index.tsx
  src/commons/mui-x/DatePickers/index.tsx
  src/hooks/onboarding/useOnboardingAdditional.ts
  src/services/auth/login/index.tsx
  src/services/onboarding/additional/complete/index.tsx
  src/services/onboarding/additional/concern/index.tsx
  src/services/onboarding/additional/emotion/index.tsx
  src/services/onboarding/additional/layout.tsx
  src/services/onboarding/basic/index.tsx
Labels: design, jiwon

#28 Feat/#24/onboarding-progressbar
  src/commons/navigation/Stepper/index.tsx
  src/services/auth/login/index.tsx
  src/services/onboarding/additional/concern/index.tsx
  src/services/onboarding/additional/emotion/index.tsx
  src/services/onboarding/additional/layout.tsx
  src/services/onboarding/basic/index.tsx
Labels: design, jiwon

#29 Feat/#25/design-chatresult
  src/assets/images/chatresult/icon_anger.svg
  src/assets/images/chatresult/icon_disgust.svg
  src/assets/images/chatresult/icon_fear.svg
  src/assets/images/chatresult/icon_happiness.svg
  src/assets/images/chatresult/icon_sadness.svg
  src/assets/images/chatresult/icon_surprise.svg
  src/commons/surfaces/Card/index.tsx
  src/commons/utils/modal/index.tsx
  src/commons/utils/modal/result.tsx
  src/services/home/index.tsx
  tailwind.config.js
Labels: design, jiwon

#30 Feat/#26/api-auth
  src/App.tsx
  src/hooks/auth/useFetchUser.ts
  src/services/auth/login/index.tsx
  src/services/auth/oauth/index.tsx
  src/services/home/index.tsx
  src/services/onboarding/additional/complete/index.tsx
  src/services/onboarding/additional/concern/index.tsx
  src/services/onboarding/additional/emotion/index.tsx
  src/services/onboarding/basic/index.tsx
  src/store/auth/index.ts
Labels: jiwon, feat

#33 add: progress
  package.json
  src/App.tsx
  src/assets/images/icon_arrow_back.svg
  src/assets/images/image_umwithfriend.svg
  src/commons/feedback/Progress/index.tsx
  src/hooks/animation/useNavigationDirection.ts
  src/hooks/onboarding/useOnboardingAdditional.ts
  src/layout.tsx
  src/services/onboarding/additional/concern/index.tsx
  src/services/onboarding/additional/emotion/index.tsx
  src/services/onboarding/basic/index.tsx
  src/services/onboarding/complete/index.tsx
  src/services/onboarding/layout.tsx
  tailwind.config.js
Labels: feat

#39 Feat/#37/design-setting
  src/App.tsx
  src/assets/images/icon_arrow_right.svg
  src/assets/images/icon_email.svg
  src/assets/images/icon_search.svg
  src/assets/images/icon_warning.svg
  src/commons/inputs/Switch/index.tsx
  src/commons/navigation/BottomNavigation/index.tsx
  src/commons/navigation/GlobalNavigation/index.tsx
  src/services/setting/component/accountdeletion/index.tsx
  src/services/setting/component/languageoption/index.tsx
  src/services/setting/component/languagesetting/index.tsx
  src/services/setting/component/passwordoption/index.tsx
  src/services/setting/component/policy/index.tsx
  src/services/setting/component/question/index.tsx
  src/services/setting/index.tsx
Labels: design, jiwon

#52 Feat/#50/refactoring-auth
  eslint.config.js
  src/App.tsx
  src/api/auth/login.ts
  src/api/fetch.ts
  src/api/onboarding/basic.ts
  src/hooks/auth/useFetchUser.ts
  src/hooks/auth/useTokenMonitor.ts
  src/services/auth/login/index.tsx
  src/services/auth/oauth/index.tsx
  src/services/onboarding/basic/constant.tsx
  src/services/onboarding/basic/index.tsx
  src/services/redirect/rootRedirect.tsx
  src/store/auth/index.ts
Labels: jiwon, feat

#59 Feat/#55/feat-chat
  src/api/chat/index.ts
  src/api/chat/websocket.ts
  src/commons/data-display/Chip/index.tsx
  src/services/home/chat/ChatInputBox/index.tsx
  src/services/home/chat/ChatSection/index.tsx
  src/services/home/chat/EndSessionModal/index.tsx
  src/services/home/chat/IntroSection/index.tsx
  src/services/home/chat/ResultSessionModal/index.tsx
  src/services/home/chat/TestSection/index.tsx
  src/services/home/chat/index.tsx
  src/store/chat/index.ts
Labels: jiwon, feat

#61 Feat/#58/feat-diagnosis
  src/App.tsx
  src/api/test/diagnosis.ts
  src/assets/images/test/answer/icon_never.svg
  src/services/home/test/AnswerToggle/group.tsx
  src/services/home/test/AnswerToggle/item.tsx
  src/services/home/test/QuestionStepperText/index.tsx
  src/services/home/test/StartCard/index.tsx
  src/services/home/test/gad/index.tsx
  src/services/home/test/index.tsx
  src/services/home/test/phq/index.tsx
  src/services/home/test/pss/index.tsx
Labels: jiwon, feat

#62 Fix/#60/fix-bug-layout
  index.html
  src/App.tsx
  src/api/chat/index.ts
  src/api/chat/websocket.ts
  src/commons/data-display/Chip/index.tsx
  src/commons/data-display/List/serveritem.tsx
  src/commons/data-display/List/userindex.tsx
  src/commons/inputs/TextField/index.tsx
  src/commons/mui-x/DatePickers/index.tsx
  src/hooks/keyboard/useKeyboardVisible.ts
  src/layout.tsx
  src/services/auth/login/index.tsx
  src/services/home/chat/ChatSection/index.tsx
  src/services/home/chat/ChatToggle/index.tsx
  src/services/home/chat/EndSessionModal/index.tsx
  src/services/home/chat/HeaderCard/index.tsx
  src/services/home/chat/IntroSection/index.tsx
  src/services/home/chat/TestSection/index.tsx
  src/services/home/chat/index.tsx
  src/services/home/test/AnswerToggle/item.tsx
  src/services/home/test/StartCard/index.tsx
  src/services/onboarding/basic/index.tsx
  src/services/setting/Policy/index.tsx
  src/services/setting/index.tsx
  tailwind.config.js
Labels: bug, jiwon

#65 Fix/#63/fix-iphone-bug
  index.html
  src/App.tsx
  src/api/auth/login.ts
  src/api/chat/index.ts
  src/api/chat/websocket.ts
  src/api/test/diagnosis.ts
  src/assets/images/test/solution/icon_time.svg
  src/assets/images/test/solution/icon_walk.svg
  src/commons/data-display/List/testgroup.tsx
  src/commons/inputs/TextField/index.tsx
  src/commons/mui-x/DatePickers/index.tsx
  src/hooks/auth/useFetchUser.ts
  src/hooks/auth/useTokenMonitor.ts
  src/hooks/keyboard/useKeyboardVisible.ts
  src/services/home/chat/IntroSection/index.tsx
  src/services/home/chat/index.tsx
  src/services/home/test/CautionTypo/index.tsx
  src/services/home/test/QuestionStepper/index.tsx
  src/services/home/test/SolutionCard/index.tsx
  src/services/home/test/SolutionModal/index.tsx
  src/services/home/test/SolutionModal/item.tsx
  src/services/home/test/index.tsx
  src/services/onboarding/basic/index.tsx
  src/services/onboarding/complete/index.tsx
  src/services/setting/index.tsx
  src/store/keyboard/index.ts
Labels: bug, design, jiwon, feat

#68 Refactor/#66/refactor-chat
  src/App.tsx
  src/api/chat/index.ts
  src/commons/navigation/BottomNavigation/index.tsx
  src/hooks/chat/useAutoScrollOnInputFocus.ts
  src/hooks/chat/useBodyScrollLockWithKeyboard.ts
  src/hooks/chat/useChatWebSocket.ts
  src/hooks/chat/useInitialChatSessionLoad.ts
  src/hooks/chat/useScrollToBottom.ts
  src/services/home/chat/IntroSection/index.tsx
  src/services/home/chat/TestSection/index.tsx
  src/services/home/chat/container.tsx
  src/services/home/chat/index.tsx
Labels: jiwon, feat
